/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "type.h"

@protocol ClassNote <NSObject>
- (AuthResponse *) login_by_email: (NSString *) email : (NSString *) password;  // throws TException
- (AuthResponse *) login_by_username: (NSString *) username : (NSString *) password;  // throws TException
- (BOOL) sign_up_email: (NSString *) email : (NSString *) password;  // throws TException
- (BOOL) sign_up_username: (NSString *) username : (NSString *) password;  // throws TException
- (BOOL) sign_out: (NSString *) auth_token;  // throws TException
- (User *) user_get: (NSString *) auth_token : (int64_t) user_id;  // throws TException
- (NSArray *) lessontable_get: (NSString *) auth_token : (int64_t) user_id;  // throws TException
- (BOOL) lessontable_set: (NSString *) auth_token : (int64_t) user_id : (NSArray *) lesson_tables;  // throws TException
- (NSArray *) courses_get_by_class: (Class *) a_class;  // throws TException
- (BOOL) course_add: (Course *) course;  // throws TException
- (BOOL) course_set: (Course *) course;  // throws TException
@end

@interface ClassNoteClient : NSObject <ClassNote> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ClassNoteProcessor : NSObject <TProcessor> {
  id <ClassNote> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithClassNote: (id <ClassNote>) service;
- (id<ClassNote>) service;
@end

@interface serviceConstants : NSObject {
}
@end
