/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum UserGender {
  UserGender_Unknown = 0,
  UserGender_Male = 1,
  UserGender_Female = 2
};

enum WeekDay {
  WeekDay_Sunday = 0,
  WeekDay_Monday = 1,
  WeekDay_Tuesday = 2,
  WeekDay_Wednesday = 3,
  WeekDay_Thursday = 4,
  WeekDay_Friday = 5,
  WeekDay_Saturday = 6
};

typedef int64_t timestamp;

@interface AuthResponse : NSObject <NSCoding> {
  NSString * __auth_token;
  timestamp __expire_in;
  int64_t __user_id;

  BOOL __auth_token_isset;
  BOOL __expire_in_isset;
  BOOL __user_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=auth_token, setter=setAuth_token:) NSString * auth_token;
@property (nonatomic, getter=expire_in, setter=setExpire_in:) timestamp expire_in;
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
#endif

- (id) initWithAuth_token: (NSString *) auth_token expire_in: (timestamp) expire_in user_id: (int64_t) user_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) auth_token;
- (void) setAuth_token: (NSString *) auth_token;
- (BOOL) auth_tokenIsSet;

- (timestamp) expire_in;
- (void) setExpire_in: (timestamp) expire_in;
- (BOOL) expire_inIsSet;

- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
- (BOOL) user_idIsSet;

@end

@interface User : NSObject <NSCoding> {
  int64_t __gid;
  NSString * __name;
  int __gender;

  BOOL __gid_isset;
  BOOL __name_isset;
  BOOL __gender_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=gid, setter=setGid:) int64_t gid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=gender, setter=setGender:) int gender;
#endif

- (id) initWithGid: (int64_t) gid name: (NSString *) name gender: (int) gender;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) gid;
- (void) setGid: (int64_t) gid;
- (BOOL) gidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (int) gender;
- (void) setGender: (int) gender;
- (BOOL) genderIsSet;

@end

@interface Lesson : NSObject <NSCoding> {
  int64_t __gid;
  NSString * __name;
  NSString * __room;

  BOOL __gid_isset;
  BOOL __name_isset;
  BOOL __room_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=gid, setter=setGid:) int64_t gid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=room, setter=setRoom:) NSString * room;
#endif

- (id) initWithGid: (int64_t) gid name: (NSString *) name room: (NSString *) room;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) gid;
- (void) setGid: (int64_t) gid;
- (BOOL) gidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (NSString *) room;
- (void) setRoom: (NSString *) room;
- (BOOL) roomIsSet;

@end

@interface Class : NSObject <NSCoding> {
  Lesson * __lesson;
  int __weekday;
  int16_t __start;
  int16_t __duration;

  BOOL __lesson_isset;
  BOOL __weekday_isset;
  BOOL __start_isset;
  BOOL __duration_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=lesson, setter=setLesson:) Lesson * lesson;
@property (nonatomic, getter=weekday, setter=setWeekday:) int weekday;
@property (nonatomic, getter=start, setter=setStart:) int16_t start;
@property (nonatomic, getter=duration, setter=setDuration:) int16_t duration;
#endif

- (id) initWithLesson: (Lesson *) lesson weekday: (int) weekday start: (int16_t) start duration: (int16_t) duration;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (Lesson *) lesson;
- (void) setLesson: (Lesson *) lesson;
- (BOOL) lessonIsSet;

- (int) weekday;
- (void) setWeekday: (int) weekday;
- (BOOL) weekdayIsSet;

- (int16_t) start;
- (void) setStart: (int16_t) start;
- (BOOL) startIsSet;

- (int16_t) duration;
- (void) setDuration: (int16_t) duration;
- (BOOL) durationIsSet;

@end

@interface typeConstants : NSObject {
}
@end
